on:
    push:
      branches:
      - main
jobs:
    Release:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 100
      - uses: fregante/release-with-changelog@v3
        with:
         token: ${{ secrets.GITHUB_TOKEN }}
         exclude: '^Meta'
         commit-template: '- {title} ← {hash}'
         template: |
           ### Changelog
           {commits}
           {range}