 - name: Read the changelog
      id: changelog
      uses: 3liz/changelog-release@0.2.0

    - name: Create release on GitHub
      uses: ncipollo/release-action@v1.10.0
      with:
        body: ${{ steps.changelog.outputs.markdown }}
        token: ${{ secrets.BOT_HUB_TOKEN }}
        allowUpdates: true